name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2020.07
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-navigator=1.9.7
  - anaconda-project=0.8.4
  - argh=0.26.2
  - asn1crypto=1.4.0
  - astroid=2.4.2
  - astropy=4.0.1.post1
  - atomicwrites=1.4.0
  - attrs=20.1.0
  - autopep8=1.5.4
  - babel=2.8.0
  - backcall=0.2.0
  - backports=1.0
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.9.1
  - bitarray=1.5.2
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.1.5
  - blosc=1.20.0
  - bokeh=2.2.0
  - boto=2.49.0
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - cairo=1.14.12
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.5.0
  - clyent=1.2.2
  - colorama=0.4.3
  - conda=4.8.4
  - conda-build=3.17.8
  - conda-env=2.6.0
  - conda-package-handling=1.6.1
  - conda-verify=3.1.1
  - contextlib2=0.6.0.post1
  - cryptography=3.0
  - curl=7.71.1
  - cycler=0.10.0
  - cython=0.29.21
  - cytoolz=0.10.1
  - dask=2.24.0
  - dask-core=2.24.0
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - distributed=2.24.0
  - docutils=0.16
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.9
  - fastcache=1.1.0
  - filelock=3.0.12
  - flake8=3.8.3
  - flask=1.1.2
  - fontconfig=2.13.0
  - freetype=2.10.2
  - fribidi=1.0.10
  - fsspec=0.8.0
  - future=0.18.2
  - get_terminal_size=1.0.0
  - gevent=20.6.2
  - glib=2.63.1
  - glob2=0.7
  - gmp=6.1.2
  - gmpy2=2.0.8
  - graphite2=1.3.14
  - greenlet=0.4.16
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - harfbuzz=1.8.8
  - hdf5=1.10.4
  - heapdict=1.0.1
  - html5lib=1.1
  - icu=58.2
  - idna=2.10
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - iniconfig=1.0.1
  - intel-openmp=2020.2
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.17.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.17.1
  - jeepney=0.4.3
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.6
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - jupyterlab=2.2.6
  - jupyterlab_server=1.2.0
  - keyring=21.3.1
  - kiwisolver=1.2.0
  - krb5=1.18.2
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libarchive=3.4.2
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - liblief=0.10.1
  - libllvm9=9.0.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - libxslt=1.1.34
  - llvmlite=0.33.0
  - locket=0.2.0
  - lxml=4.5.2
  - lz4-c=1.9.2
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - mock=4.0.2
  - more-itertools=8.4.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.1.0
  - msgpack-python=1.0.0
  - multipledispatch=0.6.0
  - navigator-updater=0.2.1
  - nb_conda_kernels=2.2.2
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - networkx=2.5
  - nltk=3.5
  - nose=1.3.7
  - notebook=5.7.10
  - numba=0.50.1
  - numexpr=2.7.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - numpydoc=1.1.0
  - olefile=0.46
  - openpyxl=3.0.5
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.1.1
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.7.0
  - partd=1.1.0
  - patchelf=0.11
  - path=15.0.0
  - path.py=12.5.0
  - pathlib2=2.3.5
  - pathtools=0.1.2
  - patsy=0.5.1
  - pcre=8.44
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.2
  - pixman=0.40.0
  - pkginfo=1.5.0.1
  - pluggy=0.13.1
  - ply=3.11
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - psutil=5.7.2
  - ptyprocess=0.6.0
  - py=1.9.0
  - py-lief=0.10.1
  - pycodestyle=2.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycrypto=2.6.1
  - pycurl=7.43.0.5
  - pydocstyle=5.1.0
  - pyflakes=2.2.0
  - pygments=2.6.1
  - pylint=2.5.3
  - pyodbc=4.0.30
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.0.1
  - python=3.7.3
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.34.1
  - python-libarchive-c=2.9
  - python_abi=3.7
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyxdg=0.26
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - qdarkstyle=2.8.1
  - qt=5.9.7
  - qtawesome=0.7.2
  - qtconsole=4.7.6
  - qtpy=1.9.0
  - readline=7.0
  - regex=2020.7.14
  - requests=2.24.0
  - ripgrep=11.0.2
  - rope=0.17.0
  - rtree=0.9.4
  - ruamel_yaml=0.15.87
  - scikit-image=0.16.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.10.1
  - secretstorage=3.1.2
  - send2trash=1.5.0
  - setuptools=49.6.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.15.0
  - snappy=1.1.8
  - snowballstemmer=2.0.0
  - sortedcollections=1.2.1
  - sortedcontainers=2.2.2
  - soupsieve=2.0.1
  - sphinx=3.2.1
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sphinxcontrib-websupport=1.2.4
  - spyder=4.1.4
  - spyder-kernels=1.9.3
  - sqlalchemy=1.3.19
  - sqlite=3.33.0
  - statsmodels=0.11.1
  - sympy=1.6.2
  - tbb=2020.2
  - tblib=1.7.0
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - toolz=0.10.0
  - tornado=6.0.4
  - tqdm=4.48.2
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.3
  - ujson=1.35
  - unicodecsv=0.14.1
  - unixodbc=2.3.7
  - urllib3=1.25.10
  - watchdog=0.10.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - wurlitzer=2.0.1
  - xlrd=1.2.0
  - xlsxwriter=1.3.3
  - xlwt=1.3.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.2
  - zict=2.0.0
  - zipp=3.1.0
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.4
  - zope.interface=4.7.1
  - zstd=1.4.5
  - pip:
    - affine==2.3.0
    - click-plugins==1.1.1
    - cligj==0.5.0
    - fiona==1.8.13.post1
    - geopandas==0.8.1
    - gis-utils-pkg-dillhicks==0.0.76
    - lasagne==0.2.dev1
    - munch==2.5.0
    - pycrs==1.0.2
    - pyproj==2.6.1.post1
    - python-dateutil==2.5.0
    - rasterio==1.1.5
    - shapely==1.7.1
    - snuggs==1.4.7
